### ISSUE TITLE
Over query limit - Google Geocode

### ISSUE THREAD

**Issue by Anjs04** [lpolepeddi/learning-flask#2]
Running this app results in this error:
`<[OVER QUERY LIMIT] Google - Geocode [empty]>`

The error occurs in models.py at this point:
```
def address_to_latlng(self, address):
    g = geocoder.google(address)
```

A key is required for the query to work.
```
{
   "error_message" : "Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}
```

Edit: The Google Geocode API requires a signup with billing details for an API key from June 2018. I switched to the Bing Maps API by signing up here (https://www.bingmapsportal.com/), and generating a key. It doesn't require any billing details. 

1. Replace `geocode.google()` with `geocode.bing()` in models.py.
2. Save the key to env with `heroku config key_bingmaps=[INSERT KEY HERE]` in the terminal.
3. Import key as variable `import os` `geocode.bing(address, key=os.environ.key_bingmaps` in models.py.

**Comment by lalithpolepeddi** [comment]
Thanks @Anjs04 for sharing your solution!
